version: '3.7'

services:
  goapp:
    build:
      context: . 
      dockerfile: docker/deploy/Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    command: sh -c "./wait && ./bin/app"
    ports:
      - 3000:3000
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=20000
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=2000
      - DB_USER=mysql
      - DB_PASSWORD=root
      - DB_HOST=mysql
      - DB_NAME=mysql-docker
      - DB_PORT=3306

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mysql-docker
    ports:
      - 3307:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
